services:
  fastapi-app:
    build: ./app
    container_name: document-processing-service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - chromadb
      - ollama
    volumes:
      - ./rag-documents:/app/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - MODEL=llama2

  chromadb:
    image: chromadb/chroma:0.4.18
    container_name: chromadb
    restart: always
    volumes:
      - chromadb_data:/chroma/chroma
    ports:
      - "8001:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
      - ANONYMIZED_TELEMETRY=FALSE

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models

volumes:
  chromadb_data:
  ollama_data:
