services:
  fastapi-app:
    build: ./app
    container_name: document-processing-service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - chromadb
      - ollama
    volumes:
      - ./rag-documents:/app/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - MODEL=llama2

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: always
    volumes:
      - chromadb_data:/chroma/chroma
    ports:
      - "8001:8000"
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_DB_DIR=/chroma/chroma
      - PERSIST_DIRECTORY=/chroma/chroma

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
    # Command to pull a model as soon as the container starts
    command: >
      sh -c "
        ollama serve &
        sleep 5
        ollama pull nomic-embed-text && 
        ollama pull llama2 && 
        wait
      "

volumes:
  chromadb_data:
  ollama_data:
